name: flutter_maps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_gemini: ^2.0.4
  google_geocoding_api: ^1.5.2
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
