name: Deploy Flask app to Google Cloud Run

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag "gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE }} --image "gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}" --region ${{ secrets.GCP_REGION }}
 